# Generated by Django 5.2 on 2025-04-06 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Universidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bolsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_com_bolsa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('link_inscricao', models.URLField()),
                ('data_limite', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('visualizacoes', models.IntegerField(default=0)),
                ('universidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolsas.universidade')),
            ],
        ),
    ]
